<?xml version="1.0" encoding="utf-8"?><Database Name="TROFOT" Class="ServerDBMLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Admin\Documents\GitHub\medSchd_v2\DB\TROFOT.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="prozect_client.Properties.Settings" SettingsPropertyName="TROFOTConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Prescription" Member="Prescriptions">
    <Type Name="Prescription">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMed" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IdClient" Type="System.String" DbType="NVarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="IdPharmacist" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="AmountMorning" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AmountNoon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AmountNight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTaking" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NumOfDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumOfDaysLeft" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastCheckDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Client_Prescription" Member="Client" ThisKey="IdClient" OtherKey="IdNumber" Type="Client" IsForeignKey="true" />
      <Association Name="Medicine_Prescription" Member="Medicine" ThisKey="IdMed" OtherKey="BrandName" Type="Medicine" IsForeignKey="true" />
      <Association Name="Pharmacist_Prescription" Member="Pharmacist" ThisKey="IdPharmacist" OtherKey="IdNumber" Type="Pharmacist" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pharmacist" Member="Pharmacists">
    <Type Name="Pharmacist">
      <Column Name="IdNumber" Type="System.String" DbType="NChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Pharmacist_Prescription" Member="Prescriptions" ThisKey="IdNumber" OtherKey="IdPharmacist" Type="Prescription" />
    </Type>
  </Table>
  <Table Name="dbo.Medicine" Member="Medicines">
    <Type Name="Medicine">
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GenericName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MedType" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TakeOption" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Medicine_Prescription" Member="Prescriptions" ThisKey="BrandName" OtherKey="IdMed" Type="Prescription" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="IdNumber" Type="System.String" DbType="NVarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Client_Prescription" Member="Prescriptions" ThisKey="IdNumber" OtherKey="IdClient" Type="Prescription" />
    </Type>
  </Table>
</Database>